%YAML:1.0
---
model_type: PINHOLE
camera_name: D435_RGB
image_width: 640
image_height: 480
distortion_parameters:
  k1: 0
  k2: 0
  p1: 0
  p2: 0
projection_parameters:
  fx: 607.592
  fy: 608.191
  cx: 322.553
  cy: 242.127