%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 1  

imu_topic: "/dji_osdk_ros/imu"
image0_topic: "//dji_osdk_ros/fpv_camera_images"
output_path: "~/output/"

cam0_calib: "dji_fpv.yaml"
image_width: 640
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Not provided

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.09647918, -0.37481299, -0.92206669, -0.01726255,
          -0.04363951, 0.92390456, -0.38012623, 0.02573858,
          0.99437788, 0.07691281, 0.0727809, 0.20151383,
          0.0, 0.0, 0.0, 1.0]
#   data: [-0.01730286, -0.99985029, 0.00002995, 0.01625795,
#          -0.01499097, 0.00022947, -0.9998876, 0.07340307,
#          0.99973791, -0.01730136, -0.01499269, 0.05160523,
#           0, 0, 0, 1]
#   data: [-0.01730286, -0.01499097,  0.99973791, -0.05021002,
#          -0.99985029,  0.00022947, -0.01730136,  0.01713152,
#           0.00002995, -0.9998876,  -0.01499269,  0.07416803,
#           0,          0,          0,          1        ]

#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.0006834818770498258   #0.0009221746732053619   # accelerometer measurement noise standard deviation.
gyr_n: 0.00010964608159786272    #0.0009221746796214183   # gyroscope measurement noise standard deviation.
acc_w: 2.773195999584313e-05       # accelerometer bias random work noise standard deviation.
gyr_w: 2.996845943467119e-06      # gyroscope bias random work noise standard deviation.
g_norm: 9.8065     # gravity magnitude

#unsynchronization parameters
estimate_td: 1                    # online estimate time offset between camera and imu
td: 0.0         # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "~/output/pose_graph/" # save and load path
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
